name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 build

      - name: Install package locally
        run: pip install -e .

      - name: Lint
        run: flake8 src tests --max-line-length=100

      - name: Tests
        run: pytest -q

      - name: Build wheel
        run: python -m build

      - name: Upload artifact (wheel)
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheel
          path: dist/*.whl

      - name: Run training (1 epoch quick test)
        run: |
          mkdir -p outputs
          python -m src.mlops_fmnist.train --epochs 1 --output_dir outputs

      - name: Upload training artifacts
        uses: actions/upload-artifact@v3
        with:
          name: training-results
          path: outputs/

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: docker build -t mlops-fmnist:ci .
